<?php

namespace UnaGauchada\FavoresBundle\Repository;

/**
 * FavorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorRepository extends \Doctrine\ORM\EntityRepository
{
}
