user_admin:
    resource: "@UserBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

user_gaucho:
        resource: "@UserBundle/Resources/config/routing/gaucho.yml"
        prefix:   /gaucho