<?php

namespace UnaGauchada\UserBundle\Repository;

/**
 * GauchoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GauchoRepository extends \Doctrine\ORM\EntityRepository
{
}
